### ISSUE TITLE
Race condition when searching inside the artists

### ISSUE THREAD

**Issue by pixelastic** [bobylito/playlistFinder#3]
This bug occured on mobile, with bad connection.

I tried to search into the SFFV for the artists, typing `Orelsan`. I had no update for a while, then I quickly saw updates for `Orel`, `Orelsan` and then it stuck on the display for just `O`. The return from the `n` request arrived after the request for the `n + x`, and the final state was not the correct one.

I don't think I can easily reproduce the issue.

![image](https://user-images.githubusercontent.com/283419/34726935-ba6fa34e-f555-11e7-8feb-43c466a15053.png)
(sorry for the flux/twilight/redshift overlay)

**Comment by bobylito** [comment]
There is a new version that is a complete overhaul of the UI. I need to check again :)

**Comment by pixelastic** [comment]
Closing as I don't think this applies anymore.

**Comment by bobylito** [comment]
👋 Thanks @pixelastic
